# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abulia
email: apoteoticos@gmail.com
description: A place for thoughts to die // Un lugar donde las ideas van a morir **/
baseurl: "/abulia" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

gems:
- jekyll-language-plugin

languages:
- es
- en

language_default: es

# Build settings
markdown: kramdown
exclude: [vendor]
